- name: Snipe IT Backup
  hosts: snipe-it
  tasks:
    - name: Create backup docker image directory
      become: true
      ansible.builtin.file:
        path: /docker/snipe-it-backup
        state: directory
        owner: jenkins
        group: jenkins
    - name: Remove backups older than 30 days
      ansible.builtin.shell:
        chdir: /docker/snipe-it-backup
        cmd: find . -type f -mtime +30 -delete
    - name: Backup database
      ansible.builtin.shell:
        cmd: >
          docker run --rm --network app-db-network mariadb:lts mysqldump 
          -h mariadb 
          -u snipeit 
          -p{{ lookup('env', 'SNIPE_IT_MARIADB_PASSWORD') }} 
          snipeit > /docker/snipe-it-backup/snipe-it-db-backup-{{ ansible_date_time.date }}.sql
    - name: Backup data directory
      community.docker.docker_container:
        name: snipe-it-data-backup
        image: ubuntu:latest
        pull: true
        detach: false
        auto_remove: true
        command: tar -cvzf /backup/snipe-it-data-backup-{{ ansible_date_time.date }}.tar.gz --directory /data .
        volumes:
          - /docker/snipe-it-backup:/backup
          - snipe-it-data:/data
    - name: Upload backups to S3
      community.aws.s3_sync:
        access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
        bucket: overlord-media-backup
        file_root: /docker/snipe-it-backup
        key_prefix: snipe-it-backups
        storage_class: DEEP_ARCHIVE
    