- name: Deploy Snipe-IT application
  hosts: snipe-it
  tasks:
    - name: Create snipeit data volume
      community.docker.docker_volume:
        name: snipe-it-data
    - name: Create snipe-it database
      community.mysql.mysql_db:
        name: snipeit
        state: present
        login_user: root
        login_password: "{{ lookup('env', 'MARIADB_ROOT_PASSWORD') }}"
    - name: Create paperless user
      community.mysql.mysql_user:
        name: snipeit
        password: "{{ lookup('env', 'SNIPE_IT_MARIADB_PASSWORD') }}"
        host: "172.%"
        priv: "snipeit.*:ALL"
        login_user: root
        login_password: "{{ lookup('env', 'MARIADB_ROOT_PASSWORD') }}"
    - name: Create snipe-it container
      community.docker.docker_container:
        name: snipe-it
        image: snipe/snipe-it:latest
        restart_policy: unless-stopped
        pull: true
        network_mode: app-db-network
        published_ports:
          - 4038:80
        volumes:
          - snipe-it-data:/var/lib/snipeit
        env:
          APP_DEBUG: "false"
          APP_ENV: production
          APP_KEY: "{{ lookup('env', 'SNIPE_IT_APP_KEY') }}"
          APP_LOCALE: en
          APP_TIMEZONE: America/New_York
          APP_URL: "{{ lookup('env', 'SNIPE_IT_URL') }}"
          MYSQL_PORT_3306_TCP_ADDR: mariadb
          MYSQL_PORT_3306_TCP_PORT: "3306"
          MYSQL_DATABASE: snipeit
          MYSQL_USER: snipeit
          MYSQL_PASSWORD: "{{ lookup('env', 'SNIPE_IT_MARIADB_PASSWORD') }}"
          PHP_UPLOAD_LIMIT: "100"