HASS_MARIADB_PASSWORD: "{{ lookup('env', 'HASS_MARIADB_PASSWORD') }}"
RECORDER_DB_URL: "mysql://homeassistant:{{ lookup('env', 'HASS_MARIADB_PASSWORD') }}@127.0.0.1/homeassistant?charset=utf8"
SPOTIFY_SP_DC: "{{ lookup('env', 'SPOTIFY_SP_DC') }}"
SPOTIFY_SP_KEY: "{{ lookup('env', 'SPOTIFY_SP_KEY') }}"
garage_exterior_camera_password: "{{ lookup('env', 'garage_exterior_camera_password') }}"