FITNESS_DB_URL: "mysql://homeassistant:{{ FITNESS_DB_PASSWORD }}@192.168.1.150/fitness?charset=utf8"
HASS_ALEXA_CLIENT_ID: "{{ HASS_ALEXA_CLIENT_ID }}"
HASS_ALEXA_CLIENT_SECRET: "{{ HASS_ALEXA_CLIENT_SECRET }}"
LIVINGROOM_TABLET_STATS_URL: "http://192.168.1.2:2323?cmd=deviceInfo&type=json&password={{ LIVINGROOM_TABLET_FULLY_KIOSK_PASSWORD }}"
RECORDER_DB_URL: "mysql://homeassistant:{{ HASS_DB_PASSWORD }}@192.168.1.87/homeassistant?charset=utf8"
SLEEPIQ_USERNAME: "{{ SLEEPIQ_USERNAME }}"
SLEEPIQ_PASSWORD: "{{ SLEEPIQ_PASSWORD }}"
XIAOMI_VACUUM_TOKEN: "{{ XIAOMI_VACUUM_TOKEN }}"
XIAOMI_VACUUM_USERNAME: "{{ XIAOMI_VACUUM_USERNAME }}"
XIAOMI_VACUUM_PASSWORD: "{{ XIAOMI_VACUUM_PASSWORD }}"