FITNESS_DB_URL: "mysql://homeassistant:{{ lookup('env', 'FITNESS-DB-PASSWORD') }}@192.168.1.150/fitness?charset=utf8"
HASS_ALEXA_CLIENT_ID: "{{ lookup('env', 'HASS-ALEXA-CLIENT-ID') }}"
HASS_ALEXA_CLIENT_SECRET: "{{ lookup('env', 'HASS-ALEXA-CLIENT-SECRET') }}"
LIVINGROOM_TABLET_STATS_URL: "http://192.168.1.2:2323?cmd=deviceInfo&type=json&password={{ lookup('env', 'LIVINGROOM-TABLET-FULLY-KIOSK-PASSWORD') }}"
RECORDER_DB_URL: "mysql://homeassistant:{{ lookup('env', 'HASS-DB-PASSWORD') }}@192.168.1.87/homeassistant?charset=utf8"
SLEEPIQ_USERNAME: "{{ lookup('env', 'SLEEPIQ-USERNAME') }}"
SLEEPIQ_PASSWORD: "{{ lookup('env', 'SLEEPIQ-PASSWORD') }}"
XIAOMI_VACUUM_TOKEN: "{{ lookup('env', 'XIAOMI-VACUUM-TOKEN') }}"
XIAOMI_VACUUM_USERNAME: "{{ lookup('env', 'XIAOMI-VACUUM-USERNAME') }}"
XIAOMI_VACUUM_PASSWORD: "{{ lookup('env', 'XIAOMI-VACUUM-PASSWORD') }}"