- name: Ubuntu Docker Server Configuration
  hosts: ubuntu_docker
  tasks:
    - name: Install prerequisites
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - python3-docker
          - python3-boto3
          - python3-pymysql
          - software-properties-common
    - name: Add Docker GPG key
      become: true
      ansible.builtin.shell:
        cmd: >-
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg
          | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
    - name: Add Stable Repository
      become: true
      ansible.builtin.shell:
        cmd: >-
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list
    - name: Install Docker Engine
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker-ce
    - name: Add jenkins user to docker group
      become: true
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: true
    - name: Copy docker logging config
      register: logging_config
      become: true
      ansibile.builtin.copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
    - name: Restart docker
      become: true
      when: logging_config.changed
      ansibile.builtin.shell:
        cmd: systemctl restart docker
