- name: Pi Hole Deployment
  hosts: pihole
  tasks:
    - name: Create docker volumes
      community.docker.docker_volume:
        name: "{{ item }}"
      loop:
        - pihole_data
        - pihole_dnsmasq
    - name: Pi Hole Container
      community.docker.docker_container:
        name: pihole
        image: pihole/pihole:latest
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - 53:53/tcp
          - 53:53/udp
          - 8053:80/tcp
        env:
          PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
          TZ: America/New_York
          VIRTUAL_PORT: "80"
        volumes:
          - pihole_data:/etc/pihole
          - pihole_dnsmasq:/etc/dnsmasq.d