import static groovy.json.JsonOutput.*

node ('docker') {
    withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
        sh 'echo $PASS | docker login -u $USER --password-stdin'
    }

    Map scmVars = checkout scm
    echo(scmVars, true)
    
    List imagesToBuild = []
    if (!scmVars.containsKey('GIT_PREVIOUS_COMMIT') || !hasSuccessfulBuild()) {
        echo "No previous commit or no previously successful build; going to build all docker images"
        imagesToBuild = findFiles(glob: 'docker/images/**/Dockerfile').collect{it.path}
    } else {
        getModifiedFiles().each {
            if (it.endsWith('/Dockerfile')) {
                imagesToBuild += it
            }
        }
    }

    if (imagesToBuild) {
        echo(imagesToBuild, true, "Building images:")
    } else {
        echo "No images to build"
    }
}