- name: Create .ssh directory
  ansible.builtin.file:
    path: ~/.ssh
    owner: jenkins
    group: jenkins
    state: directory
    mode: "0700"
- name: Add authorized_keys
  ansible.builtin.copy:
    src: jenkins.pub
    dest: ~/.ssh/authorized_keys
    owner: jenkins
    group: jenkins
    mode: "0600"
