- name: FTP Setup
  hosts: ftp
  tasks:
    - name: Install FTP server and passlib library
      become: true
      ansible.builtin.apt:
        update_cache: true
        name: 
          - python3-passlib
          - vsftpd
    - name: Create paperless FTP user
      become: true
      ansible.builtin.user:
        name: ftpuser
        groups: jenkins
        password: "{{ lookup('env', 'FTP_USER_PASSWORD') | password_hash }}"
        home: /docker/ftpuser
    - name: Create ftp directories
      become: true
      ansible.builtin.file:
        path: "/docker/ftpuser/{{ item }}"
        state: directory
        owner: ftpuser
        group: jenkins
      loop:
        - paperless
        - receipts
    - name: Enable FTP write
      become: true
      register: enable_ftp_write
      ansible.builtin.lineinfile:
        dest: /etc/vsftpd.conf
        line: write_enable=YES
    - name: Restart FTP service
      become: true
      when: enable_ftp_write.changed
      ansible.builtin.shell:
        cmd: systemctl restart vsftpd.service