version: '3.2'
services:
  appdaemon:
    container_name: appdaemon
    restart: unless-stopped
    image: mfugate/appdaemon:4.0.5
    volumes:
      - /docker/appdaemon/secrets.yaml:/conf/secrets.yaml
      - /docker/appdaemon/apps/secrets.py:/conf/apps/secrets.py
    ports:
      - "5050:5050"
  certbot:
    container_name: certbot
    restart: unless-stopped
    image: certbot/certbot:v1.21.0
    volumes:
      - /docker/certbot/conf:/etc/letsencrypt
      - /docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  duplicati:
    container_name: duplicati
    restart: unless-stopped
    image: duplicati/duplicati:canary
    volumes: 
      - /docker/duplicati:/data
      - /docker:/docker
    ports:
      - "8200:8200"
  home-assistant:
    container_name: home-assistant
    restart: unless-stopped
    image: homeassistant/home-assistant:2021.11.2
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /docker/home-assistant:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    privileged: true
  mosquitto:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto:2.0.13
    volumes:
      - /docker/server-management/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/nginx:/etc/nginx/conf.d
      - /docker/certbot/conf:/etc/letsencrypt
      - /docker/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  unifi:
    container_name: unifi
    restart: unless-stopped
    image: jacobalberty/unifi:v6.4.54
    volumes:
      - /docker/unifi:/unifi
    environment:
      - RUNAS_UID0=false
      - TZ=America/New_York
      - UNIFI_UID=1000
      - UNIFI_GID=1000
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "6789:6789"
      - "10001:10001"
volumes:
  mosquitto_data:
  mosquitto_log: