- name: Home Assistant Backup
  hosts: homeassistant
  tasks:
    - name: Upload backups to S3
      community.aws.s3_sync:
        access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
        bucket: overlord-media-backup
        file_root: /docker/home-assistant/backups
        key_prefix: home-assistant-backups/mike
        storage_class: DEEP_ARCHIVE
        delete: true