version: "3.8"
services:
  home-assistant:
    depends_on:
      - zwavejs
    container_name: home-assistant
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - hass_config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    privileged: true
  mqtt:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mqtt-data:/var/lib/mysql
      - /home/jenkins/server-management/sarah/mosquitto.conf:/mosquitto/config/mosquitto.conf
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    restart: unless-stopped
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - nginx-data:/data
      - letsencrypt:/etc/letsencrypt
  ps5-mqtt:
    container_name: ps5-mqtt
    restart: unless-stopped
    image: ghcr.io/funkeyflo/ps5-mqtt/amd64:latest
    network_mode: host
    environment:
      ACCOUNT_CHECK_INTERVAL: "5000"
      CREDENTIAL_STORAGE_PATH: /config/credentials.json
      DEVICE_CHECK_INTERVAL: "5000"
      DEVICE_DISCOVERY_INTERVAL: "60000"
      FRONTEND_PORT: "8645"
      INCLUDE_PS4_DEVICES: "false"
      MQTT_HOST: "192.168.50.229"
      MQTT_PORT: "1883"
      PSN_ACCOUNTS: /run/secrets/ps5_mqtt_account
    secrets:
      - ps5_mqtt_account
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_SCHEDULE: '0 5 1 * * *'
  zwavejs:
    container_name: zwavejs
    restart: unless-stopped
    image: zwavejs/zwave-js-ui:latest
    ports:
      - 8091:8091
      - 3000:3000
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - zwavejs_config:/usr/src/app/store
volumes:
  hass_config:
  letsencrypt:
  mqtt-data:
  nginx-data:
  zwavejs_config:
secrets:
  ps5_mqtt_account:
    file: sony.conf