version: "3.2"
services:
  certbot:
    container_name: certbot
    restart: unless-stopped
    image: certbot/certbot:${CERTBOT_VERSION}
    volumes:
      - /docker/certbot/conf:/etc/letsencrypt
      - /docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  home-assistant:
    container_name: home-assistant
    restart: unless-stopped
    image: homeassistant/home-assistant:${HASS_VERSION}
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /docker/home-assistant:/config
      - /docker/home-assistant-test:/test-config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    privileged: true
  mosquitto:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto:${MOSQUITTO_VERSION}
    volumes:
      - /docker/server-management/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    restart: unless-stopped
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx-data:/data
      - letsencrypt:/etc/letsencrypt
  unifi:
    container_name: unifi
    restart: unless-stopped
    image: jacobalberty/unifi:${UNIFI_VERSION}
    volumes:
      - /docker/unifi:/unifi
    environment:
      - RUNAS_UID0=false
      - TZ=America/New_York
      - UNIFI_UID=1000
      - UNIFI_GID=1000
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "6789:6789"
      - "10001:10001"
volumes:
  mosquitto_data:
  mosquitto_log:
  letsencrypt:
  nginx-data:
