- name: Immich Backup
  hosts: immich
  tasks:
    - name: Create backup docker image directory
      become: true
      ansible.builtin.file:
        path: /docker/immich-backup
        state: directory
        owner: jenkins
        group: jenkins
    - name: Remove backups older than 3 days
      ansible.builtin.shell:
        chdir: /docker/immich-backup
        cmd: find . -type f -mtime +2 -delete
    - name: Backup database
      ansible.builtin.shell:
        cmd: docker exec -t immich_postgres pg_dumpall --clean --if-exists --username immich > /docker/immich-backup/immich-database-{{ ansible_date_time.date }}.sql
    - name: Backup data
      ansible.builtin.shell:
        cmd: tar cvzf /docker/immich-backup/immich-upload-{{ ansible_date_time.date }}.tar.gz --directory /docker/immich/upload library upload
    - name: Upload backups to S3
      community.aws.s3_sync:
        access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
        bucket: overlord-media-backup
        file_root: /docker/immich-backup
        key_prefix: immich-backups
        storage_class: DEEP_ARCHIVE
        delete: true