- name: Make sure we have a 'wheel' group
  become: true
  ansible.builtin.group:
    name: wheel
    state: present
- name: Allow 'wheel' group to have passwordless sudo
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
- name: Add sudoers users to wheel group
  become: true
  ansible.builtin.user:
    name: jenkins
    groups: wheel
    append: true
