---
- name: Get Key Vault
  azure.azcollection.azure_rm_keyvault_info:
    name: overlord-vault
    resource_group: Overlord
  register: keyvault

- name: Get secrets
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "{{ keyvault['keyvaults'][0]['vault_uri'] }}"
    name: "{{ item | replace('_', '-') }}"
  register: vaultSecrets
  loop: "{{ secrets_list }}"

- name: Set secrets
  set_fact:
    "{{ item.item | replace('-', '_') }}": "{{ item.secrets[0].secret }}"
  loop: "{{ vaultSecrets.results }}"

- name: Save Secrets List
  set_fact:
    secrets_to_retrieve: "{{ secrets_list }}"