- name: Frigate
  hosts: frigate
  tasks:
    - name: Create frigate config directory
      become: true
      ansible.builtin.file:
        path: /docker/frigate
        state: directory
        owner: jenkins
        group: jenkins
    - name: Create frigate config
      register: config
      ansible.builtin.template:
        src: config.yml
        dest: /docker/frigate/config.yml
    - name: Create media volumes
      community.docker.docker_volume:
        name: frigate_media
    - name: Frigate container
      register: container
      community.docker.docker_container:
        name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - 1935:1935
          - 5000:5000
          - 8554:8554
          - 8555:8555/tcp
          - 8555:8555/udp
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /docker/frigate:/config
          - frigate_media:/media/frigate
        devices:
          - /dev/bus/usb:/dev/bus/usb
          - /dev/dri/renderD128
    - name: Restart container if config changed but container didn't change
      when: config.changed and not container.changed
      ansible.builtin.shell:
        cmd: docker restart frigate