version: '3.8'
services:
  jenkins:
    container_name: jenkins
    restart: unless-stopped
    user: jenkins
    privileged: true
    image: mfugate/jenkins:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/jenkins/jenkins-secrets.properties:/run/secrets/secrets.properties
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
volumes:
  jenkins_home: