---
- name: Load Azure Secrets
  hosts: localhost
  gather_facts: False
  vars:
    secrets_to_retrieve:
      - DOCKER1_IP
      - HASS_PORT
      - JENKINS_PORT
      - OVERLORD_HOSTNAME
      - TRUENAS_DOCKER_IP
  tasks:
    - name: Load Azure Secrets
      import_tasks: ../../ansible/load_azure_secrets.yml
      vars:
        secrets_list: "{{ secrets_to_retrieve }}"

- name: Deploy Nginx Config
  hosts: docker1
  tasks:
    - name: Set template variables
      loop: "{{ hostvars['localhost']['secrets_to_retrieve'] }}"
      set_fact: 
        "{{ item }}": "{{ hostvars['localhost'][item] }}"
    - name: Copy nginx config from template
      ansible.builtin.template:
        src: app.conf
        dest: ~/nginx/
        mode: '0400'
    
