- name: Update and upgrade packages
  hosts: "{{ host | default('apt') }}"
  tasks:
    - name: Update and upgrade packages
      become: true
      ansible.builtin.apt:
        autoremove: true
        update_cache: true
        upgrade: true
    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      become: true
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
