# Run ubuntu-docker playbook first

- name: Paperless-NGX
  hosts: paperless
  tasks:
    - name: Create paperless database
      community.mysql.mysql_db:
        name: paperless
        state: present
        login_user: root
        login_password: "{{ lookup('env', 'MARIADB_ROOT_PASSWORD') }}"
    - name: Create paperless user
      community.mysql.mysql_user:
        name: paperless
        password: "{{ lookup('env', 'PAPERLESS_MARIADB_PASSWORD') }}"
        host: "172.%"
        priv: "paperless.*:ALL"
        login_user: root
        login_password: "{{ lookup('env', 'MARIADB_ROOT_PASSWORD') }}"
    - name: Create docker volumes
      community.docker.docker_volume:
        name: "{{ item }}"
      loop:
        - redis_data
        - paperless_data
    - name: Create docker directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
      loop:
        - /docker/paperless/media
        - /docker/paperless/export
        - /docker/paperless/consume
    - name: Redis Container
      community.docker.docker_container:
        name: paperless-broker
        image: docker.io/library/redis:7
        restart_policy: unless-stopped
        pull: true
        network_mode: app-db-network
        volumes:
          - redis_data:/data
    - name: Gotenberg Container
      community.docker.docker_container:
        name: gotenberg
        image: docker.io/gotenberg/gotenberg:7.10
        restart_policy: unless-stopped
        pull: true
        network_mode: app-db-network
        command:
          - gotenberg
          - "--chromium-disable-javascript=true"
          - "--chromium-allow-list=file:///tmp/.*"
    - name: Tika Container
      community.docker.docker_container:
        name: tika
        image: ghcr.io/paperless-ngx/tika:latest
        restart_policy: unless-stopped
        pull: true
        network_mode: app-db-network
    - name: Paperless Webserver Container
      community.docker.docker_container:
        name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        restart_policy: unless-stopped
        pull: true
        network_mode: app-db-network
        published_ports:
          - 8000:8000
        volumes:
          - paperless_data:/usr/src/paperless/data
          - /docker/paperless/media:/usr/src/paperless/media
          - /docker/paperless/export:/usr/src/paperless/export
          - /docker/paperless/consume:/usr/src/paperless/consume
        env:
          PAPERLESS_REDIS: redis://paperless-broker:6379
          PAPERLESS_DBENGINE: mariadb
          PAPERLESS_DBHOST: mariadb
          PAPERLESS_DBPASS: "{{ lookup('env', 'PAPERLESS_MARIADB_PASSWORD') }}"
          PAPERLESS_DBPORT: "3306"
          PAPERLESS_SECRET_KEY: "{{ lookup('env', 'PAPERLESS_SECRET_KEY') }}"
          PAPERLESS_TIKA_ENABLED: "1"
          PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
          PAPERLESS_TIKA_ENDPOINT: http://tika:9998
          PAPERLESS_TRUSTED_PROXIES: 192.168.1.0/24,172.0.0.0/8
          PAPERLESS_URL: "{{ lookup('env', 'PAPERLESS_URL') }}"
          PAPERLESS_USE_X_FORWARD_HOST: "true"
    - name: Create paperless FTP user
      become: true
      ansible.builtin.user:
        name: paperless
        group: paperless
        groups: jenkins
        password: "{{ lookup('env', 'PAPERLESS_MARIADB_PASSWORD') }}"
        home: /docker/paperless/consume
    - name: Install FTP server
      ansible.builtin.apt:
        update_cache: true
        name: vsftpd
    - name: Enable FTP write
      become: true
      register: enable_ftp_write
      ansible.builtin.lineinfile:
        dest: /etc/vsftpd.conf
        line: write_enable=YES
    - name: Restart FTP service
      become: true
      when: enable_ftp_write.changed
      ansible.builtin.shell:
        cmd: systemctl restart vsftpd.service