- name: Paperless Backup
  hosts: paperless
  tasks:
    - name: Create backup docker image directory
      become: true
      ansible.builtin.file:
        path: /docker/paperless-backup
        state: directory
        owner: jenkins
        group: jenkins
    - name: Remove backups older than 30 days
      ansible.builtin.shell:
        chdir: /docker/paperless-backup
        cmd: find . -type f -mtime +30 -delete
    - name: Backup database
      ansible.builtin.shell:
        cmd: >
          docker run --rm --network paperless-network mariadb:lts mysqldump 
          -h paperless-mariadb 
          -u paperless 
          -p{{ lookup('env', 'PAPERLESS_MARIADB_PASSWORD') }} 
          paperless > /docker/paperless-backup/paperless-db-backup-{{ ansible_date_time.date }}.sql
    - name: Backup media directory
      ansible.builtin.shell:
        chdir: /docker/paperless/media
        cmd: tar -cvzf /docker/paperless-backup/paperless-media-backup-{{ ansible_date_time.date }}.tar.gz .
    - name: Upload backups to S3
      community.aws.s3_sync:
        access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
        bucket: overlord-media-backup
        file_root: /docker/paperless-backup
        key_prefix: paperless-backups
        storage_class: DEEP_ARCHIVE
    