# Run ubuntu-docker playbook first

- name: Paperless-NGX
  hosts: paperless
  tasks:
    - name: Create docker network
      community.docker.docker_network:
        name: paperless-network
    - name: Create docker volumes
      community.docker.docker_volume:
        name: "{{ item }}"
      loop:
        - mariadb-data
        - redis_data
        - paperless_data
    - name: Create docker directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
      loop:
        - /docker/paperless/media
        - /docker/paperless/export
        - /docker/paperless/consume
    - name: MariaDB container
      community.docker.docker_container:
        name: paperless-mariadb
        image: mariadb:lts
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - 3306:3306
        volumes:
          - mariadb-data:/var/lib/mysql
        env:
          MARIADB_ROOT_PASSWORD: "{{ lookup('env', 'PAPERLESS_MARIADB_ROOT_PASSWORD') }}"
          MARIADB_USER: paperless
          MARIADB_PASSWORD: "{{ lookup('env', 'PAPERLESS_MARIADB_PASSWORD') }}"
          MARIADB_DATABASE: paperless
    - name: Redis Container
      community.docker.docker_container:
        name: broker
        image: docker.io/library/redis:7
        restart_policy: unless-stopped
        pull: true
        network_mode: paperless-network
        volumes:
          - redis_data:/data
    - name: Gotenberg Container
      community.docker.docker_container:
        name: gotenberg
        image: docker.io/gotenberg/gotenberg:7.10
        restart_policy: unless-stopped
        pull: true
        network_mode: paperless-network
        command:
          - gotenberg
          - "--chromium-disable-javascript=true"
          - "--chromium-allow-list=file:///tmp/.*"
    - name: Tika Container
      community.docker.docker_container:
        name: tika
        image: ghcr.io/paperless-ngx/tika:latest
        restart_policy: unless-stopped
        pull: true
        network_mode: paperless-network
    - name: Paperless Webserver Container
      community.docker.docker_container:
        name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        restart_policy: unless-stopped
        pull: true
        network_mode: paperless-network
        published_ports:
          - 8000:8000
        state: stopped
        volumes:
          - paperless_data:/usr/src/paperless/data
          - /docker/paperless/media:/usr/src/paperless/media
          - /docker/paperless/export:/usr/src/paperless/export
          - /docker/paperless/consume:/usr/src/paperless/consume
        env:
          PAPERLESS_REDIS: redis://broker:6379
          PAPERLESS_DBENGINE: mariadb
          PAPERLESS_DBHOST: paperless-mariadb
          PAPERLESS_DBPASS: "{{ lookup('env', 'PAPERLESS_MARIADB_PASSWORD') }}"
          PAPERLESS_DBPORT: "3306"
          PAPERLESS_TIKA_ENABLED: "1"
          PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
          PAPERLESS_TIKA_ENDPOINT: http://tika:9998