- name: Create a PS5-MQTT Container
  hosts: ps5mqtt
  tasks:
    - set_fact:
        psn_accounts:
          - username: "{{ lookup('env', 'PSN_USER') }}"
            npsso: "{{ lookup('env', 'PSN_NPSSO') }}"
            preferred_ps5: 78C8818DF671
    - name: Create docker volume
      community.docker.docker_volume:
        name: ps5mqtt_data
    - name: PS5-MQTT Container
      community.docker.docker_container:
        name: ps5mqtt
        image: ghcr.io/funkeyflo/ps5-mqtt/amd64:latest
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        entrypoint: /app/run-standalone.sh
        volumes:
          - ps5mqtt_data:/config
        env:
          ACCOUNT_CHECK_INTERVAL: "5000"
          CREDENTIAL_STORAGE_PATH: /config/credentials.json
          DEVICE_CHECK_INTERVAL: "5000"
          DEVICE_DISCOVERY_INTERVAL: "60000"
          FRONTEND_PORT: "8645"
          INCLUDE_PS4_DEVICES: "false"
          MQTT_HOST: "192.168.1.86"
          MQTT_PORT: "1883"

          # Using | string gives a result with single quotes.
          # This method results in valid json with double quotes instead. 
          # Otherwise, ps5-mqtt will throw a parsing error.
          PSN_ACCOUNTS: "{{ psn_accounts | to_json }}" 