- name: Create a PS5-MQTT Container
  hosts: ps5mqtt
  tasks:
    - name: Create ps5mqtt config directory
      ansible.builtin.file:
        path: /docker/ps5mqtt
        state: directory
        owner: jenkins
        group: jenkins
    - name: Create run.sh
      ansible.builtin.copy:
        src: files/ps5mqtt/run.sh
        dest: /docker/ps5mqtt/run.sh
        mode: "0777"
    - name: PS5-MQTT Container
      community.docker.docker_container:
        name: ps5mqtt
        image: ghcr.io/funkeyflo/ps5-mqtt/amd64:latest
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        entrypoint: /config/run.sh
        env:
          ACCOUNT_CHECK_INTERVAL: "5000"
          CREDENTIAL_STORAGE_PATH: /config/credentials.json
          DEVICE_CHECK_INTERVAL: "5000"
          DEVICE_DISCOVERY_INTERVAL: "60000"
          FRONTEND_PORT: "8645"
          INCLUDE_PS4_DEVICES: "false"
          MQTT_HOST: "127.0.0.1"
          MQTT_PORT: "1883"
          PSN_ACCOUNTS: >
            [
              {
                "username": "{{ lookup('env', 'PSN_USER') }}",
                "npsso": "{{ lookup('env', 'PSN_NPSSO') }}"
              }
            ] | string
        volumes:
          - /docker/ps5mqtt:/config