- name: Raspberry Pi Squeezelite
  hosts: "{{ host | default('raspi_squeezelite_hdmi') }}"
  tasks:
    - name: Start Squeezelite Docker Container
      community.docker.docker_container:
        name: squeezelite
        image: giof71/squeezelite:latest
        restart_policy: unless-stopped
        privileged: true
        devices:
          - /dev/snd
        env:
          SQUEEZELITE_SERVER_PORT: 192.168.1.32
          SQUEEZELITE_NAME: "{{ inventory_hostname }}"
          SQUEEZELITE_AUDIO_DEVICE: default:CARD=sndrpihifiberry
          SQUEEZELITE_MAC_ADDRESS: "{{ CLIENTMAC }}"
          DISABLE_MAC_ADDRESS_GENERATION: "yes"
