- name: Ubuntu Docker Server Configuration
  hosts: "{{ host | default('ubuntu_docker') }}"
  tasks:
    - name: Update and upgrade packages
      become: true
      ansible.builtin.apt:
        autoremove: true
        update_cache: true
        upgrade: true
    - name: Install prerequisites
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - python3-docker
          - software-properties-common
    - name: Add Docker GPG key
      become: true
      ansible.builtin.shell:
        cmd: >-
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg
          | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
    - name: Add Stable Repository
      become: true
      ansible.builtin.shell:
        cmd: >-
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Install Docker Engine
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker-ce
      args:
        creates: /usr/bin/docker
    - name: Add jenkins user to docker group
      become: true
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: true
