- name: File Shares
  hosts: fileshare
  tasks:
    - name: Install samba
      become: true
      ansible.builtin.apt:
        update_cache: true
        name: 
          - samba
    - name: Create shared directories
      become: true
      ansible.builtin.file:
        path: "/home/jenkins/{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
      loop:
        - paperless
        - scans
    - name: Enable samba share
      become: true
      register: add_samba_share_config
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        prepend_newline: true
        block: |
          [scans]
             path = /home/jenkins/scans
             read only = no
             browsable = yes
             guest ok = yes
             create mask = 666
             directory mask = 777
             force user = jenkins
             force group = jenkins

          [paperless]
             path = /home/jenkins/paperless
             read only = no
             browsable = yes
             guest ok = yes
             create mask = 666
             directory mask = 777
             force user = jenkins
             force group = jenkins
    - name: Restart Samba Service
      become: true
      when: add_samba_share_config.changed
      ansible.builtin.shell:
        cmd: systemctl restart smbd.service