- name: ZwaveJS Server
  hosts: zwavejs
  tasks:
    - name: Create docker volume
      community.docker.docker_volume:
        name: zwavejs-data
    - name: ZwaveJS Container
      community.docker.docker_container:
        name: zwavejs
        image: zwavejs/zwave-js-ui:latest
        restart_policy: unless-stopped
        pull: true
        devices:
          - /dev/ttyACM0:/dev/ttyACM0
        env:
          TZ: America/New_York
        published_ports:
          - 3000:3000
          - 8091:8091
        volumes:
          - zwavejs-data:/usr/src/app/store
